---
title: "dataviz-makeover-2"
description: |
  A short description of the post.
author:
  - name: Jovinka Hartanto
    url: https://www.linkedin.com/in/jovinkahartanto/
date: 06-10-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Introduction
Nowadays, data visualisation such as graphs and maps can be found anywhere. Data visualisation can help us to understand better what the information means and it will also make it easier to understand the trends, patterns, and outliers within large datasets. However, a poor data visualisation can be misleading or make it even harder to understand the information. 

This post will makeover the chart below, so that it can be more fruitful for the audience. The data visualisation will be created by using data provided by Department of Statistics, Singapore (DOS). The data are available under the sub-section of [Merchandise Trade by Region/Market](https://www.singstat.gov.sg/find-data/search-by-theme/trade-and-investment/merchandise-trade/latest-data).

# 2. Critique of Visualisation 
To explore different perspective and design more truthful and enlightening data visualisation, we will first observe the original visualisation. The critiques will be divided into two section, clarity and aesthetics.

## 2.1 Clarity

## 2.2 Aesthetics


# 3. Alternative Design
# Clarity:

# Aesthetics:


# 4. Step-by-Step Guide

## 4.1 Data Preparation

Remove the data that is outside the study period. The study period for this study is between January 2011 to December 2020.
